# Default output filenames
output_fn_name: multiqc_report_chromeqc.html
data_dir_name: multiqc_data_chromeqc

extra_fn_clean_exts:
    - .tsv
    - .csv

# Ignore these files / directories / paths when searching for logs
fn_ignore_files:
    - .DS_Store
fn_ignore_dirs:
    - annoying_dirname
fn_ignore_paths:
    - '*/path/to/*_files/'

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500              # Swap tables for a beeswarm plot above this

custom_data:
    chromeqc_molecule_size:
        file_format: 'csv'
        section_name: 'Molecule size'
        description: 'Density plots of Chromium molecule size'
        plot_type: 'linegraph'
sp:
    chromeqc_molecule_size:
        fn: '*chromqc_molecule_size.csv'
