# Title to use for the report.
title: ChromeQC

# Default output filenames
output_fn_name: multiqc_report_chromeqc.html
data_dir_name: multiqc_data_chromeqc

extra_fn_clean_exts:
    - .tsv
    - .csv

# Ignore these files / directories / paths when searching for logs
fn_ignore_files:
    - .DS_Store
fn_ignore_dirs:
    - annoying_dirname
fn_ignore_paths:
    - '*/path/to/*_files/'

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500              # Swap tables for a beeswarm plot above this

custom_logo: null         # '/path/to/logo.png'
custom_logo_url: https://github.com/hackseq/2017_project_6     # 'https://www.example.com'
custom_logo_title: HERE   # 'Our Institute Name'
subtitle: Summarize sequencing library quality of 10x Genomics Chromium linked reads            # Grey text below title
intro_text: False          # Set to False to remove, or your own text

custom_data:
    order:
        - molecule_size
        - unmatched_barcodes
        - whitelist_barcodes
    molecule_size:
        file_format: 'csv'
        section_name: 'Molecule size'
        description: 'Density plots of Chromium molecule size'
        plot_type: 'linegraph'
    unmatched_barcodes:
        file_format: 'tsv'
        section_name: 'Unmatched barcode distribution'
        description: 'Number of reads in each barcode that is not on the white list'
        plot_type: 'linegraph'
    whitelist_barcodes:
        file_format: 'tsv'
        section_name: 'White list barcode distribution'
        description: 'Number of reads in each barcode that is on the white list'
        plot_type: 'linegraph'

sp:
    molecule_size:
        fn: '*chromqc_molecule_size.csv'
    unmatched_barcodes:
        fn: '*unmatched_barcodes_population_counts.tsv'
    whitelist_barcodes:
        fn: '*whitelist_barcodes_population_counts.tsv'
